public class AccountPfTriggerHandler extends TriggerHandler {
    
    protected override void beforeInsert(List<SObject> listNew) {

    }
    
    protected override void beforeUpdate(Map<Id, SObject> mapNew, Map<Id, SObject> mapOld) {

    }
    
    protected override void beforeDelete(Map<Id, SObject> mapOld) {

    }
    
    protected override void afterInsert(Map<Id, SObject> mapNew) {

    }
    
    protected override void afterUpdate(Map<Id, SObject> mapNew, Map<Id, SObject> mapOld) {

    }
    
    protected override void afterDelete(Map<Id, SObject> mapOld) {
		
    }
    
    protected override void afterUndelete(Map<Id, SObject> mapNew) {
		
    }
}
